apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: base-image-
spec:
  entrypoint: build-base-image
  arguments:
    parameters:
    - name: tag
      value: latest
  templates:
  - name: build-base-image
    inputs:
      parameters:
      - name: tag
    steps:
    - - name: mirror-image
        templateRef:
          name: flavor-image-mirror-template
          template: main
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-base.git
          - name: git_version
            value: main
          - name: repo_name
            value: quay.io/bradfordwagner/base
          - name: tag
            value: "{{inputs.parameters.tag}}"
          - name: push
            value: ""
          - name: upstream_repo
            value: "{{ item.repo }}"
          - name: upstream_tag
            value: "{{ item.tag }}"
        withItems:
        - { repo: 'debian', tag: 'buster' }
        - { repo: 'debian', tag: 'bullseye' }
        - { repo: 'alpine', tag: '3.12' }
        - { repo: 'alpine', tag: '3.13' }
        - { repo: 'alpine', tag: '3.14' }
        - { repo: 'ubuntu', tag: 'bionic' }
        - { repo: 'ubuntu', tag: 'focal' }

