apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: base-image-
spec:
  entrypoint: build-base-image
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: build-base-image
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    steps:
    - - name: mirror-image
        templateRef:
          name: flavor-image-mirror-template
          template: "{{inputs.parameters.git_ref_type}}"
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-base.git
          - name: git_version
            value: "{{inputs.parameters.git_version}}"
          - name: repo_name
            value: quay.io/bradfordwagner/base
          - name: upstream_repo
            value: "{{ item.repo }}"
          - name: upstream_tag
            value: "{{ item.tag }}"
          - name: runtime_platforms
            value: "{{ item.runtime_platforms }}"
        withItems:
        - { repo: 'debian', tag: 'buster'  , runtime_platforms: [linux/amd64, linux/arm, linux/arm64, linux/386    , linux/mips64le, linux/ppc64le , linux/s390x] }
        - { repo: 'debian', tag: 'bullseye', runtime_platforms: [linux/amd64, linux/arm, linux/arm64, linux/386    , linux/mips64le, linux/ppc64le , linux/s390x] }
        - { repo: 'alpine', tag: '3.12'    , runtime_platforms: [linux/amd64, linux/arm, linux/arm64, linux/386    , linux/ppc64le , linux/s390x] }
        - { repo: 'alpine', tag: '3.13'    , runtime_platforms: [linux/amd64, linux/arm, linux/arm64, linux/386    , linux/ppc64le , linux/s390x] }
        - { repo: 'alpine', tag: '3.14'    , runtime_platforms: [linux/amd64, linux/arm, linux/arm64, linux/386    , linux/ppc64le , linux/s390x] }
        - { repo: 'ubuntu', tag: 'bionic'  , runtime_platforms: [linux/amd64, linux/arm, linux/arm64, linux/386    , linux/ppc64le , linux/s390x] }
        - { repo: 'ubuntu', tag: 'focal'   , runtime_platforms: [linux/amd64, linux/arm, linux/arm64, linux/ppc64le, linux/riscv64 , linux/s390x] }


