name: docker-mirror-tags
on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: checkout=taskfiles
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
      - name: qemu
        uses: docker/setup-qemu-action@v3
      - name: docker_buildx=v0.13.1
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.13.1
      - name: login=quay.io
        run: ${{ secrets.QUAY_LOGIN }}
