name: docker-mirror-tags
on:
  push:
    tags:
      - '*'
jobs:
  config-yaml:
    name: config.yaml
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - uses: actions/checkout@v4
      # https://github.com/chrisdickinson/setup-yq/blob/latest/action.yml
      - uses: chrisdickinson/setup-yq@v1.0.1
        name: yq=v4.43.1
        with:
          yq-version: v4.43.1
      - name: jq=1.7
        uses: dcarbone/install-jq-action@v2
        with:
          version: 1.7
      - name: export=config
        id: config
        run: echo "config=$(yq -oj '.' config.yaml | jq -cr)" >> $GITHUB_OUTPUT
  tags:
    runs-on: ubuntu-latest
    needs: config-yaml
    name: ${{ matrix.mirror.repo }}_${{ matrix.mirror.tag }}
    strategy:
      fail-fast: false
      matrix:
        mirror: ${{ fromJSON(needs.config-yaml.outputs.config).mirrors }}
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: checkout=taskfiles
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
      
      - name: qemu
        uses: docker/setup-qemu-action@v3
      - name: docker_buildx=v0.13.1
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.13.1
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: task=tags
        run: |
          task -t ./taskfiles/tasks/containers/mirror.yml \
            build \
            repo=${{ matrix.mirror.repo }} \
            repo_tag=${{ matrix.mirror.tag }} \
            platforms=${{ join(matrix.mirror.platforms,',') }} \
            target_repo=${{ fromJSON(needs.config-yaml.outputs.config).target_repo }} \
            target_tag=${{ github.ref_name }} \
            is_tag=true
