name: docker-mirror-tags
on:
  push:
    tags:
      - '*'
jobs:
  cartesian-product:
    name: cartesian_product
    runs-on: ubuntu-latest
    outputs:
      mirrors: ${{ steps.mirrors.outputs.mirrors }}
      config: ${{ steps.config.outputs.config }}
    steps:
      - uses: actions/checkout@v4
      # https://github.com/chrisdickinson/setup-yq/blob/latest/action.yml
      - uses: chrisdickinson/setup-yq@v1.0.1
        name: yq=v4.43.1
        with:
          yq-version: v4.43.1
      - name: jq=1.7
        uses: dcarbone/install-jq-action@v2
        with:
          version: 1.7
      - name: resolve_mirrors
        id: mirrors
        run: echo "mirrors=$(yq -oj '.mirrors' config.yaml | jq -cr)" >> $GITHUB_OUTPUT
      - name: resolve_target_repo
        id: target_repo
        run: echo "config=$(yq -oj '.' config.yaml | jq -cr)" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs: cartesian-product
    name: ${{ matrix.mirror.repo }}-${{ matrix.mirror.tag }}
    strategy:
      fail-fast: false
      matrix:
        mirror: ${{ fromJSON(needs.cartesian-product.outputs.mirrors) }}
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: checkout=taskfiles
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
      - name: qemu
        uses: docker/setup-qemu-action@v3
      - name: docker_buildx=v0.13.1
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.13.1
      - name: login=quay.io
        run: ${{ secrets.QUAY_LOGIN }}
